---

- hosts: localhost

  tasks:

  - name: Run apt upgrade
    apt:
      upgrade: yes

  - name: Install Apache2
    apt:
      name: apache2
      state: installed

  - name: Set ServerName in apache2.conf
    lineinfile:
      path: /etc/apache2/apache2.conf
#      regexp: '^ServerName'
      line: 'ServerName 10.0.0.105'
      backup: yes
      insertafter: EOF

  - name: Install MySQL
    apt:
      name: mysql-server
      state: installed

  - name: Install PHP
    apt:
      name: "{{ item }}"
      state: installed
    with_items:
      - php
      - libapache2-mod-php
      - php-mcrypt
      - php-mysql

  - name: Modify dir.conf DirIndex order
    lineinfile:
      path: /etc/apache2/mods-enabled/dir.conf
      regexp: "^DirectoryIndex"
      line: "DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm"
      backup: yes

  - name: Add zoneminder repository
    apt_repository:
      repo: 'ppa:iconnor/zoneminder'

  - name: Install Zoneminder
    apt:
      name: zoneminder
      state: installed

  - name: Add www-data and video user
    user:
      name: "{{ item }}"
    with_items:
      - www-data
      - video

  - name: Change ownersship of zm dir to www-data
    file:
      path: /usr/share/zoneminder/
      owner: www-data
      group: www-data
      recurse: yes
    
  - name: Enable apache modules
    apache2_module:
      state: present
      name: "{{ item }}"
    with_items:
      - cgi
      - rewrite

  - name: Enable zoneminder config
    command: a2enconf zoneminder